---
title: "FAQs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Hydrology Index

##### *Effective Impervious Area (EIA)*

**The Rock Creek mainstem includes both the MS4 and CSS. The Rock Creek watershed also includes additional area beyond the Rock Creek SCI subwatersheds. What area of Rock Creek is used for the SCI analysis?**

The entire Rock Creek watershed is used in the SCI analysis. See the "eia_rock_creek" tab in the lookup spreadsheet for a full list of subsheds included.

<br>

# Human Health Index

##### *Dumpsites, Trash, E. coli*

**What timeframe is used for the trash and dumpsite analyses?**

Since the analysis uses data from the Rapid Stream Assessments (RSA), the timeframe can vary and is not limited to a set five year period. The most recent data from each assessment point and reach is used.

<br>

# Water Quality Index

##### *Dissolved Oxygen, Turbidity, Conductivity, Temperature, Nitrogen, Phosphorus, pH*

**How are non-detects handled in the dataset?**

The reporting limit is used for non-detect values. For example, results reported as \<0.010, got incorporated in the analysis as 0.010.

**What water quality criteria should be used for the various parameters?**

See Section 1 (Indicators and Metrics) of the Stream Condition Index Methodology (2022)

Among the non-nutrient WQ indicators, some have only a maximum criteria, only a minimum criteria, or both a maximum and minimum criteria. The same assess_wq() function handles all three cases.

For the nutrient WQ indicatiors (TN and TP), the assess_wq_nutrients() requires both criteria input for the Piedmont and Coastal Plain Level III Ecoregions

<br>

# Aquatic Life Index

##### *Fish, Habitat, Macroinvertebrate, Connection to the Mainstem*

**How are the aquatic life metrics calculated?** 

All four metrics get calculated outside of the R package and get incorporated through lookup tables in data/lookup_tables.xlsx.

Connection to the Mainstem is unlikely to change from year to year. Subsheds are assigned a score of either 10 (connected to the mainstem) or 1 (not connected to the mainstem).

An option for calculating fish IBI, habitat PHI, and macroinvertebrate HBI is with the [MBSStools R package](https://leppott.github.io/MBSStools/articles/MBSStools_vignette.html).  The IBI, PHI, and HBI scores then get translated to an SCI score and added to the relevant lookup table.

**How do IBI, PHI, and HBI scores translate to SCI scores?**

See the conversion tables below:

| SCI Score |  Fish IBI  | Macro HBI  | Habitat PHI |
|:---------:|:----------:|:----------:|:-----------:|
|    10     | 4.7 - 5.0  |  0 - 1.5   |  90 - 100   |
|     9     | 4.4 - 4.69 | 1.51 - 3.5 |  85 - 89.9  |
|     8     | 4.0 - 4.39 | 3.51 - 4.5 |  80 - 84.9  |
|     7     | 3.5 - 3.99 | 4.51 - 5.5 |  75 - 79.9  |
|     6     | 3.0 - 3.49 | 5.51 - 6.5 |  70 - 74.9  |
|     5     | 2.5 - 2.99 | 6.51 - 7.5 |  65 - 69.9  |
|     4     | 2.0 - 2.49 | 7.51 - 8.5 |  57 - 64.9  |
|     3     | 1.5 - 1.99 | 8.51 - 9.5 |  50 - 56.9  |
|     2     | 1.0 - 1.49 | 9.51 - 10  |  25 - 49.9  |
|     1     |  No fish   | No macros  |  0 - 24.9   |

<br>

# Stations

**What stations are included for each tributary?**

All station locations within a given tributary should be incorporated into the analysis and included in the location_id lookup table.

For Rock Creek, only include stations specifically in Upper Rock Creek and Lower Rock Creek.

**Are separate scores calculated for the upper and lower segments of Rock Creek and Watts Branch?**

No, a single score is calculated for each indicator in Rock Creek and Watts Branch

<br>

# Timeframe

**What timeframe should be used for the analysis?**

The goal is to use the five most recent calendar years of data (e.g. 01/01/2020 -- 12/31/2024). Some exceptions may be made to extend the timeframe beyond five years if it is found that there is inadequate data.

<br>

# Troubleshooting

**When I try to run the R code, I get a warning. What should I do?**

Most warnings are expected and are not an issue when running the R code. You should be able to proceed through steps as normal. If you still have questions or concerns, contact the package maintainer (see 'Contacts' subsection of the FAQs)

**When I try to run the R code, I get an error. What should I do?**

Possible things to try include:

-   Read the error message to see if you can pinpoint where the error occurred.

-   ·Be sure that all input variables are specified and correct.

-   Confirm file names and pathways are correct.

-   Check whether datasets have format changes. Changes in field names, changes in waterbody names, new sampling IDs, etc. can disrupt the code.

-   If you're unable to resolve the error, If you still have questions or concerns, contact the package maintainer (see 'Contacts' subsection of the FAQs)

<br>

# Contact

**Who should I contact if I have questions about the R package?**

The R package is currently being maintained by Shanna Rucker Blount (LimnoTech). You can contact her at srucker\@limno.com
